# Generated by Django 5.2.3 on 2025-06-15 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser or client device information at sign in.', null=True, verbose_name='User Agent')),
                ('event_type', models.CharField(choices=[('sign_in', 'Sign In'), ('refresh', 'Token Refresh')], default='sign_in', help_text='Type of authentication event.', max_length=20, verbose_name='Event Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sign_ins', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Auth Log',
                'verbose_name_plural': 'Auth Logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
